version: '2.1'
services:
  mongodb:
    image: mongo:4.1
    container_name: mongodb
    mem_limit: 2048m
    restart: always
    volumes:
      - ./mongodata:/data/db:rw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    restart: always
    mem_limit: 4096m
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1/data:/usr/share/elasticsearch/data:rw

  graylog:
    image: graylog/graylog:4.2.4
    volumes:
      - ./graylog/:/usr/share/graylog/
      - "/etc/localtime:/etc/localtime:ro"
    container_name: graylog
    restart: always
    environment:
    - TZ=Europe/Moscow
    - GRAYLOG_TIMEZONE=Europe/Moscow
    - GRAYLOG_ROOT_TIMEZONE=Europe/Moscow
    - root_timezone=Europe/Moscow
    # CHANGE ME!
    - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
    # Password: admin
    - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    - GRAYLOG_WEB_ENDPOINT_URI=http://10.19.236.77:9000/api/
    - GRAYLOG_HTTP_EXTERNAL_URI=http://10.19.236.77:9000/
    - GRAYLOG_SERVER_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # HTTP
      - 9090:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

